### ISSUE TITLE
LISP-INI file

### ISSUE THREAD

**Issue by TheFausap** [blakemcbride/PSL#1]
Hello,

I'm trying to use the raw lisp interpreter.
Reading the README file, I understand that if I run "make lisp" a LISP-INI file should be generated, 

`Note that the process of building anything but the raw interpreter builds an initialization file named LISP-INI. This file is specific to the related lisp executable created.`

but this is not happening.
The README also says that for the raw lisp interpreter a LISP-INI file is not required at all. So, I would like to understand if the LISP-INI file should be present or not.

thanks,
Fausto

**Comment by TheFausap** [comment]
Ok, sorry... re-reading the phrase I understood in the wrong way :) My English is not perfect at all... sorry about that.
I have another question about the PSL itself, is this the same LISP used to build the REDUCE CAS Algebra System?

**Comment by blakemcbride** [comment]
If I remember correctly, the base system doesn't require a LISP-INI file.  Extensions to the base system (like the compiler or your application) will cause the system to generate the LISP-INI file which must be linked in.

Without doing anything different than what's shown, is it not working as it's supposed to?

**Comment by blakemcbride** [comment]
I think it is.  However, personally, I never had an interest in the REDUCE system and never looked at it.  My interest was in a small, fast lisp which this system is.  I thought it would be interesting to do more with it, I just never got the time.

**Comment by TheFausap** [comment]
> If I remember correctly, the base system doesn't require a LISP-INI file. Extensions to the base system (like the compiler or your application) will cause the system to generate the LISP-INI file which must be linked in.

indeed this works as expected when I generate the lisp compiler.

> 
> Without doing anything different than what's shown, is it not working as it's supposed to?

the tests work without any problem, so it's not required at all.

By the way, I compiled it under OpenVMS Alpha and it worked perfectly with the DEC C compiler. So it's very portable indeed!

**Comment by TheFausap** [comment]
> I think it is. However, personally, I never had an interest in the REDUCE system and never looked at it. My interest was in a small, fast lisp which this system is. I thought it would be interesting to do more with it, I just never got the time.

Exactly, this lisp is very fast and that's the reason I like it REDUCE compared to MAXIMA. And REDUCE created also a symbolic LISP, called RLISP (and based on PSL) that's very interesting.
